version: '3'
services:
  app:
    build: app
    networks:
      - app-network
  load_balancer:
    build: nginx
    ports:
      - 8080:80
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:

